sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - develop
cache:
  directories:
  - node_modules
before_install:
- cd app
- npm update
install:
- npm install
script:
- npm test
- jest --coverage && coveralls < coverage/lcov.info